# Generated by Django 4.1.1 on 2023-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.CharField(default='2015', max_length=4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
    ]
